In [1]:
import numpy as np

In [52]:
sigma1 = 0.38
sigma2 = 0.12
sigma11 = np.power(sigma1,2)
sigma22 = np.power(sigma2,2)
rho = 0.3
sigma12 = rho*sigma1*sigma2
r0= 0.10

In [53]:
mu = np.array([[0.20],[0.13]])
mu_t = np.array([[0.2,0.13]])
mu_e = np.array([[0.1],[0.03]])
mu_e_t = np.array([[0.1,0.03]])
Sigma = np.array([[sigma11, sigma12],[sigma12, sigma22]])
Sigma_inverse = np.linalg.inv(Sigma)
one_v = np.array([[1.0],[1.0]])
one_v_t = np.array([[1.0,1.0]])

In [56]:
top = np.dot(Sigma_inverse, mu_e)
B = np.dot(one_v_t, Sigma_inverse)
B = np.dot(B, mu)
A = np.dot(one_v_t, Sigma_inverse)
A = r0*np.dot(A, one_v)
bottom = B-A
w_t = top/bottom
w_t_T = np.array([[0.2578125,0.7421875]])
print(w_t)

[[0.2578125]
 [0.7421875]]


In [47]:
mu_portfolio = r0 + np.dot(w_t_T,mu_e)
print(mu_portfolio)
sigma_p2 = np.dot(w_t_T, Sigma)
sigma_p2 = np.dot(sigma_p2, w_t)
sigma_p = np.sqrt(sigma_p2)
print(sigma_p2)
print(sigma_p)

[[0.14748229]]
[[0.01734598]]
[[0.13170412]]


In [57]:
1/bottom

array([[0.4738125]])

In [58]:
sigma12

0.013679999999999998

In [59]:
t1 = 17*w_t
t2= np.dot(Sigma_inverse, mu_e)
(t1/t2-(10/0.2)-(3/1.25))*(1/4)

array([[-11.08629688],
       [-11.08629688]])

In [76]:
M=17.0
W1=10.0
W2=3.0
W3=4.0
gamma = 0.4738125
gamma1 = 0.2
gamma2 = 1.25

In [81]:
gamma3 = W3/((M*gamma)-(W1*gamma1)-(W2*gamma2))
gamma3

1.7354990915746937

In [82]:
1/gamma3

0.5762031250000001

In [83]:
gamma_values = np.array([0.2,1.25,0.5762031250000001])
gamma_values.mean()

0.6754010416666668

In [84]:
wealth = np.array([10.0,3.0,4.0])
summation = 0.0
for i in range(len(wealth)):
    valuex = (wealth[i]/17)*gamma_values[i]
    summation += valuex

In [85]:
summation

0.4738125000000001

In [105]:
W_1 = gamma_values[2]*np.dot(Sigma_inverse, mu_e)
W_1_T = np.matrix.transpose(W_1)

In [106]:
np.dot(W_1_T, one_v)

array([[1.21609946]])

In [107]:
1-np.dot(W_1_T, one_v)

array([[-0.21609946]])

In [137]:
W_1[1][0]

0.21237030996609177

In [ ]:
import pandas as pd

In [151]:
gamma_values = np.array([0.2,1.25,0.5762031250000001])
weights = {'investor':[],'risk_free':[], 'Asset_1':[], 'Asset_2':[]}
for i in range(len(gamma_values)):
    W_1 = (gamma_values[i])*np.dot(Sigma_inverse, mu_e)
    Asset_1 = W_1[0][0]
    Asset_2 = W_1[1][0]
    risk_free = 1 - Asset_1 - Asset_2
    weights['investor'].append(i+1)
    weights['risk_free'].append(risk_free)
    weights['Asset_1'].append(Asset_1)
    weights['Asset_2'].append(Asset_2)
weights = pd.DataFrame.from_dict(weights)
weights = weights.set_index('investor')
weights

risk_free   Asset_1   Asset_2
investor                               
1          0.577892  0.108825  0.313283
2         -1.638174  0.680154  1.958020
3         -0.216099  0.313526  0.902574

In [146]:
weights

investor  risk_free   Asset_1   Asset_2
0         1   0.577892  0.108825  0.313283
1         2  -1.638174  0.680154  1.958020
2         3  -0.216099  0.313526  0.902574