In [21]:
import numpy as np
import pandas as pd

In [2]:
#Givens
sigma1 = 0.38
sigma2 = 0.12
sigma11 = np.power(sigma1,2)
sigma22 = np.power(sigma2,2)
rho = 0.3
sigma12 = rho*sigma1*sigma2
r0= 0.10

In [3]:
#Givens and calculations
mu = np.array([[0.20],[0.13]])
mu_t = np.array([[0.2,0.13]])
mu_e = np.array([[0.1],[0.03]])
mu_e_t = np.array([[0.1,0.03]])
Sigma = np.array([[sigma11, sigma12],[sigma12, sigma22]])
Sigma_inverse = np.linalg.inv(Sigma)
one_v = np.array([[1.0],[1.0]])
one_v_t = np.array([[1.0,1.0]])

In [4]:
#part a Weight calculation
top = np.dot(Sigma_inverse, mu_e)
B = np.dot(one_v_t, Sigma_inverse)
B = np.dot(B, mu)
A = np.dot(one_v_t, Sigma_inverse)
A = r0*np.dot(A, one_v)
bottom = B-A
w_t = top/bottom
w_t_T = np.array([[0.2578125,0.7421875]])
print(w_t)

[[0.2578125]
 [0.7421875]]


In [5]:
mu_portfolio = r0 + np.dot(w_t_T,mu_e)
print(mu_portfolio)
sigma_p2 = np.dot(w_t_T, Sigma)
sigma_p2 = np.dot(sigma_p2, w_t)
sigma_p = np.sqrt(sigma_p2)
print(sigma_p2)
print(sigma_p)

[[0.14804688]]
[[0.02276521]]
[[0.15088144]]


In [9]:
M=17.0
W1=10.0
W2=3.0
W3=4.0
gamma = 0.4738125
gamma1 = 0.2
gamma2 = 1.25

In [28]:
#Check that gamma values are correct
wealth = np.array([10.0,3.0,4.0])
gamma_values = np.array([0.2,1.25,0.5762031250000001])
summation = 0.0
for i in range(len(wealth)):
    valuex = (wealth[i]/17)*gamma_values[i]
    summation += valuex
summation

0.4738125000000001

In [27]:
gamma_values = np.array([0.2,1.25,0.5762031250000001])
weights = {'investor':[],'risk_free':[], 'Asset_1':[], 'Asset_2':[]}
for i in range(len(gamma_values)):
    W_1 = (gamma_values[i])*np.dot(Sigma_inverse, mu_e)
    Asset_1 = W_1[0][0]
    Asset_2 = W_1[1][0]
    risk_free = 1 - Asset_1 - Asset_2
    weights['investor'].append(i+1)
    weights['risk_free'].append(risk_free)
    weights['Asset_1'].append(Asset_1)
    weights['Asset_2'].append(Asset_2)
weights = pd.DataFrame.from_dict(weights)
weights = weights.set_index('investor')
weights['sum'] = weights.sum(axis=1)
weights

risk_free   Asset_1   Asset_2  sum
investor                                    
1          0.577892  0.108825  0.313283  1.0
2         -1.638174  0.680154  1.958020  1.0
3         -0.216099  0.313526  0.902574  1.0

In [38]:
gamma_values = np.array([0.2,1.25,0.5762031250000001])
summation = 0.0
for i in range(len(gamma_values)):
    W_1 = (gamma_values[i])*np.dot(Sigma_inverse, mu_e)
    value = wealth[i]*W_1
    summation += value 
market = 17*w_t
print('Transpose Investor side: ', np.transpose(summation))
print('Transpose Market side: ', np.transpose(market))

Transpose Investor side:  [[ 4.3828125 12.6171875]]
Transpose Market side:  [[ 4.3828125 12.6171875]]


In [41]:
summation = 0.0
for i in range(len(weights)):
    value = wealth[i]*weights['risk_free'][i+1]
    summation += value
print(summation)

1.3322676295501878e-15


In [44]:
summation = 0.0
for i in range(len(weights)):
    value = (wealth[i] - wealth[i]*weights['risk_free'][i+1])*w_t 
    summation += value
print('Sum of Demand from all investors (Transpose):', np.transpose(summation))
print('Sum of Supply from market (Transpose)', np.transpose(market))

Sum of Demand from all investors (Transpose): [[ 4.3828125 12.6171875]]
Sum of Supply from market (Transpose) [[ 4.3828125 12.6171875]]


In [62]:
mu_market = r0 + np.dot((np.transpose(w_t)),mu_e)
mu_market

array([[0.14804687]])

In [72]:
mu_market = r0 + np.dot((np.transpose(w_t)),mu_e)
Beta_1 = (0.1)/(mu_market[0][0]-r0)
Beta_2 = (0.03)/(mu_market[0][0]-r0)
print('Beta_1: ', Beta_1)
print('Beta_2: ', Beta_2)

Beta_1:  2.0813008130081307
Beta_2:  0.6243902439024391


In [74]:
Beta_2*(mu_market-r0)

array([[0.03]])

2.0813008130081307 0.6243902439024391


In [61]:
mu_market = r0 + np.dot((np.transpose(w_t)),mu_e)
top = np.dot(Sigma, w_t)
x1 = np.dot((np.transpose(w_t)),Sigma)
bottom = np.dot(x1,w_t)
total_value = (top/bottom)*(mu_market[0][0]-r0)
print('Computed value of mu_e (Transpose): ', np.transpose(total_value))
print('Original value of mu_e (Transpose): ', np.transpose(mu_e))

Computed value of mu_e (Transpose):  [[0.1  0.03]]
Original value of mu_e (Transpose):  [[0.1  0.03]]


In [59]:
total_value

array([[0.1 ],
       [0.03]])

In [66]:
x3 = np.dot((np.transpose(w_t)),Sigma)
value = np.dot(x3, w_t)
print(value)
print(sigma11, sigma22)

[[0.02276521]]
0.1444 0.0144
